// Generated by Dagger (https://dagger.dev).
package com.ecocustomerapp.ui.fragments.main.local;

import com.ecocustomerapp.ui.base.BaseFragment_MembersInjector;
import dagger.MembersInjector;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class LocalFragment_MembersInjector implements MembersInjector<LocalFragment> {
  private final Provider<LocalViewModel> mViewModelProvider;

  public LocalFragment_MembersInjector(Provider<LocalViewModel> mViewModelProvider) {
    this.mViewModelProvider = mViewModelProvider;
  }

  public static MembersInjector<LocalFragment> create(Provider<LocalViewModel> mViewModelProvider) {
    return new LocalFragment_MembersInjector(mViewModelProvider);}

  @Override
  public void injectMembers(LocalFragment instance) {
    BaseFragment_MembersInjector.injectMViewModel(instance, mViewModelProvider.get());
  }
}
