// Generated by Dagger (https://dagger.dev).
package com.ecocustomerapp.ui.fragments.main.airport;

import com.ecocustomerapp.ui.base.BaseFragment_MembersInjector;
import dagger.MembersInjector;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class AirportFragment_MembersInjector implements MembersInjector<AirportFragment> {
  private final Provider<AirportViewModel> mViewModelProvider;

  public AirportFragment_MembersInjector(Provider<AirportViewModel> mViewModelProvider) {
    this.mViewModelProvider = mViewModelProvider;
  }

  public static MembersInjector<AirportFragment> create(
      Provider<AirportViewModel> mViewModelProvider) {
    return new AirportFragment_MembersInjector(mViewModelProvider);}

  @Override
  public void injectMembers(AirportFragment instance) {
    BaseFragment_MembersInjector.injectMViewModel(instance, mViewModelProvider.get());
  }
}
