// Generated by Dagger (https://dagger.dev).
package com.ecocustomerapp.ui.fragments.main.outstation;

import com.ecocustomerapp.ui.base.BaseFragment_MembersInjector;
import dagger.MembersInjector;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class OutstationFragment_MembersInjector implements MembersInjector<OutstationFragment> {
  private final Provider<OutstationViewModel> mViewModelProvider;

  public OutstationFragment_MembersInjector(Provider<OutstationViewModel> mViewModelProvider) {
    this.mViewModelProvider = mViewModelProvider;
  }

  public static MembersInjector<OutstationFragment> create(
      Provider<OutstationViewModel> mViewModelProvider) {
    return new OutstationFragment_MembersInjector(mViewModelProvider);}

  @Override
  public void injectMembers(OutstationFragment instance) {
    BaseFragment_MembersInjector.injectMViewModel(instance, mViewModelProvider.get());
  }
}
